# Generated by Django 6.0 on 2026-01-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pslapp', '0004_alter_user_cnic_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='join_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
